CREATE TABLE [dbo].[AnswersheetQuestionwiseMarkHistory](
    [AnswersheetQuestionwiseMarkHistoryId] [bigint] IDENTITY(1,1) NOT NULL,
	[AnswersheetQuestionwiseMarkId] [bigint] NOT NULL,
	[AnswersheetId] [bigint] NOT NULL,
	[QuestionNumber] [int] NOT NULL,
	[QuestionNumberSubNum] [int] NOT NULL,
	[QuestionPartName] [nvarchar](10) NOT NULL,
	[QuestionGroupName] [nvarchar](10) NOT NULL,
	[MaximumMark] [decimal](5, 2) NOT NULL,
	[ObtainedMark] [decimal](5, 2) NOT NULL,
	[IsActive] [bit] NULL,
	[CreatedDate] [datetime] NOT NULL,
	[CreatedById] [bigint] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
	[ModifiedById] [bigint] NOT NULL)