CREATE TABLE [dbo].[DocumentDetails]
(
	[DocumentId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[DocumentName] NVARCHAR(255) NOT NULL,
	[DocumentUrl] NVARCHAR(255) NOT NULL,
	[IsActive] BIT DEFAULT 1,
	CreatedDate DATETIME DEFAULT GETDATE(),
	CreatedById BIGINT NOT NULL,
	ModifiedDate DATETIME DEFAULT GETDATE(),
	ModifiedById BIGINT NOT NULL
)
