CREATE TABLE [dbo].[Institutions]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Email] NVARCHAR(255) NOT NULL,
	[MobileNumber] NVARCHAR(15) NOT NULL,
	IsActive BIT DEFAULT 1,
    CreatedDate DATETIME DEFAULT GETDATE(),
    CreatedBy NVARCHAR(255) NOT NULL,
    ModifiedDate DATETIME DEFAULT GETDATE(),
    ModifiedBy NVARCHAR(255) NOT NULL
)
