CREATE TABLE [dbo].[Institution]
(
	[InstitutionId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Code] NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(500) NULL,
	[Email] NVARCHAR(255) NOT NULL,
	[MobileNumber] NVARCHAR(15) NOT NULL,
	IsActive BIT DEFAULT 1,
    CreatedDate DATETIME DEFAULT GETDATE(),
    CreatedById BIGINT NOT NULL,
    ModifiedDate DATETIME DEFAULT GETDATE(),
    ModifiedById BIGINT NOT NULL
)
