CREATE TABLE [dbo].[QPDocumentBookMark]
(
	[QPDocumentBookMarkId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[QPDocumentId] BIGINT NOT NULL FOREIGN KEY (QPDocumentId) REFERENCES [QPDocument](QPDocumentId),
	[BookMarkName] NVARCHAR(50) NOT NULL,
	[BookMarkText] NVARCHAR(MAX) NOT NULL,
	[IsActive] BIT DEFAULT 1,
	CreatedDate DATETIME DEFAULT GETDATE(),
	CreatedById BIGINT NOT NULL DEFAULT 1,
	ModifiedDate DATETIME DEFAULT GETDATE(),
	ModifiedById BIGINT NOT NULL DEFAULT 1
)
