CREATE TABLE [dbo].[QPDocumentBookMark]
(
	[QPDocumentBookMarkId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[QPTemplateId] BIGINT NOT NULL FOREIGN KEY (QPTemplateId) REFERENCES [QPTemplate](QPTemplateId),
	[DocumentId] BIGINT NOT NULL FOREIGN KEY (DocumentId) REFERENCES [Document](DocumentId),
	[BookMarkName] NVARCHAR(50) NOT NULL,
	[BookMarkText] NVARCHAR(MAX) NOT NULL,
	[IsActive] BIT DEFAULT 1,
	CreatedDate DATETIME DEFAULT GETDATE(),
	CreatedById BIGINT NOT NULL DEFAULT 1,
	ModifiedDate DATETIME DEFAULT GETDATE(),
	ModifiedById BIGINT NOT NULL DEFAULT 1
)
