CREATE TABLE [dbo].[QPTags]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Tag] NVARCHAR(50) NOT NULL UNIQUE,
	[TagDataType] NVARCHAR(50) NOT NULL,
	[IsQuestion] BIT NOT NULL,
	[Description] NVARCHAR(255) NOT NULL,
	[IsActive] BIT DEFAULT 1,
	CreatedDate DATETIME DEFAULT GETDATE(),
	CreatedById BIGINT NOT NULL,
	ModifiedDate DATETIME DEFAULT GETDATE(),
	ModifiedById BIGINT NOT NULL
)
