CREATE TABLE [dbo].[QPTag]
(
	[QPTagId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(255) NOT NULL,
	[Tag] NVARCHAR(255) NOT NULL UNIQUE,
	[TagDataTypeId] BIGINT NOT NULL,
	[IsQuestion] BIT NOT NULL,
	[IsActive] BIT DEFAULT 1,
	CreatedDate DATETIME DEFAULT GETDATE(),
	CreatedById BIGINT NOT NULL,
	ModifiedDate DATETIME DEFAULT GETDATE(),
	ModifiedById BIGINT NOT NULL
)
