CREATE TABLE [dbo].[QPTemplate]
(
	[QPTemplateId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[QPTemplateName] NVARCHAR(255) NOT NULL,
	[QPTemplateStatusTypeId] BIGINT NOT NULL,
	[QPCode] NVARCHAR(255) NOT NULL,
	[CourseId] BIGINT NOT NULL,
	[RegulationYear] NVARCHAR(255) NOT NULL,
	[BatchYear] NVARCHAR(255) NOT NULL,
	[DegreeTypeId] BIGINT NOT NULL,
	[ExamYear] NVARCHAR(255) NOT NULL,
	[ExamMonth] NVARCHAR(255) NOT NULL,
	[ExamType] NVARCHAR(255) NOT NULL,
	[Semester] BIGINT NOT NULL,
	[StudentCount] BIGINT NOT NULL,
	[IsActive] BIT DEFAULT 1,
	CreatedDate DATETIME DEFAULT GETDATE(),
	CreatedById BIGINT NOT NULL,
	ModifiedDate DATETIME DEFAULT GETDATE(),
	ModifiedById BIGINT NOT NULL
)
