CREATE TABLE [dbo].[QPTemplates]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(255) NOT NULL,
	InstitutionId BIGINT NOT NULL,
	DepartmentId BIGINT NOT NULL,
	CourseId BIGINT NOT NULL,
	QPTemplateDocumentId BIGINT NOT NULL,
	QPTemplateAnswerDocumentId BIGINT NOT NULL ,
	QPTemplateSyallbusDocumentId BIGINT NOT NULL ,
	[IsActive] BIT DEFAULT 1,
	CreatedDate DATETIME DEFAULT GETDATE(),
	CreatedById BIGINT NOT NULL,
	ModifiedDate DATETIME DEFAULT GETDATE(),
	ModifiedById BIGINT NOT NULL
)
