CREATE TABLE [dbo].[QPTemplateDocument]
(
	[QPTemplateDocumentId] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[QPTemplateId] BIGINT NOT NULL,
	[QPDocumentTypeId] BIGINT NOT NULL,
	[DocumentId] BIGINT NOT NULL,
	[IsActive] BIT DEFAULT 1,
	CreatedDate DATETIME DEFAULT GETDATE(),
	CreatedById BIGINT NOT NULL DEFAULT 1,
	ModifiedDate DATETIME DEFAULT GETDATE(),
	ModifiedById BIGINT NOT NULL DEFAULT 1
)
