CREATE TABLE Role (
    RoleId BIGINT IDENTITY(1,1) PRIMARY KEY,
    [Name] NVARCHAR(50) NOT NULL UNIQUE,
    IsActive BIT DEFAULT 1,
    CreatedDate DATETIME DEFAULT GETDATE(),
    CreatedById BIGINT NOT NULL,
    ModifiedDate DATETIME DEFAULT GETDATE(),
    ModifiedById BIGINT NOT NULL
);