CREATE TABLE Roles (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE,
    IsActive BIT DEFAULT 1,
    CreatedDate DATETIME DEFAULT GETDATE(),
    CreatedBy NVARCHAR(255) NOT NULL,
    ModifiedDate DATETIME DEFAULT GETDATE(),
    ModifiedBy NVARCHAR(255) NOT NULL
);